### These settings are synced to GitHub by https://probot.github.io/apps/settings/
### read how to config: https://github.com/probot/settings/blob/master/README.md
### And see https://developer.github.com/v3/repos/#edit for all available settings.

repository:
   
   ## The name of the repository. Changing this will rename the repository
   #name: repo-name
   
   ## A short description of the repository that will show up on GitHub
   #description: This is the description of this github repository.
   
   ## A comma-separated list of topics to set on the repository
   #topics: game,app,art,concept,futur,client,server,network,linux,video,editor,production,engineering,cad,3d
   
   ## A URL with more information about the repository
   #homepage: https://example.github.io/
   

   ## `true` to make the repository private or `false` to make it public.
   #private: false

   ## the default branch for this repository.
   default_branch: master

   ## if true squash all the commits in pull requests for finaly merge only one commit on head of the branch .
   allow_squash_merge: false
   ## allow or not to create a new branch for merging commits in the pull request on the head of the branch.
   allow_merge_commit: false
   ## rebase-merging keep all the commits of the pull requests and add them on the branch head.
   allow_rebase_merge: true
   

   ### Features
   
   ## `true` to integrate the 'task tracking' or `false` to disable it.
   has_issues: true

   ## `true` for enable or `false` to disable the 'projects board'.
   ## (If projects are disabled for the organization, passing `true` will cause an API error.)
   has_projects: false
   ## All of This for Only That... is my thinking when i see the utility of the 'projects board'.
   ## Maybe with required approving review on a pull request 'projects board' will appear more usefull.
   ## for now lets just use milestones and personal 'projects boards'

   ## `true` to enable the wiki or `false` to disable it.
   has_wiki: false
   ## i dont want spend contributions efforts in gh-page AND wiki documentation.
   ## i prefere we focus on just one type of documentation.
   ## gh-page seems easier to integrate in realases for offline documentation and keep the same collaboration process
   ## but GitHub Pages are always public, even if the repo they’re coming form is private. 

   ## Set to true or false to enable/disable the !deprecated! downloads features on the repository..
   #has_downloads: false


   
## define Labels for Issues and Pull Requests
labels:
   
 - name: referred
   color: 007700
   description:  pullrequest applyed on opened issue
 - name: confirmed
   color: 5319e7
   description: reliable content, confirmed by many people ( can be reproduced if an issue)
 - name: employed
   color: ededed
   description: issues with some pullrequest dedicated about
 - name: duplication
   color: bfdadc
   description: duplicate an already existing issue that have been reported before.
 - name: filled
   color: bfd4f2
   description: Issues reported on the good way. with all fields filled
 - name: irrelevant
   color: fbca04
   description: unrelated improper inappropriate incongruous inept inapt.
   
 - name: newfeature-type
   color: 009800
   description: asking for a new functionality to be added. 
 - name: enhancement-type
   color: 1d76db
   description: ask for modification of an existing feature.
 - name: question-type
   color: cc317c
   description: need help or have something to ask, (e.g. how to do something)
 - name: feedback-type
   color: 006b75
   description: give tests and analyse that could help for project development.
 - name: bug-type
   color: b71c1c
   description: about unintended behaviours that need correction.
   
 - name: high-priority
   color: b60205
   description: important critical Emergency, require urgent action.
 - name: normal-priority
   color: cccccc
   description:  concerning common issues.
 - name: low-priority
   color: f9d0c4
   description:  trivial and minor topics, will be proced if nothing more serious.
   
 - name: novice-user
   color: fc97b2
   description: issues made by beginners contributor
 - name: average-user
   color: 7057ff
   description: issues made by intermediate contributor
 - name: expert-user
   color: 7057ff
   description: issues made by high experienced contributor
   
 - name: english-language
   color: 8ed9e2
   description: software language in use
 - name: french-language
   color: 8ed9e2
   description: software language in use
 - name: italian-language
   color: 8ed9e2
   description: software language in use
 - name: portuguese-language
   color: 8ed9e2
   description: software language in use
 - name: russian-language
   color: 8ed9e2
   description: software language in use
 - name: spanish-language
   color: 8ed9e2
   description: software language in use
 - name: arabic-language
   color: 8ed9e2
   description: software language in use
 - name: chinese-language
   color: 8ed9e2
   description: software language in use
   
 - name: 2.4.3-version
   color: 8ed9e2
   description: software Version concerned
 - name: 1.2.3-version
   color: 8ed9e2
   description: software Version concerned
 - name: beta-version
   color: 8ed9e2
   description: software Version concerned
   
 - name: laptop-device
   color: fad8c7
   description: computers with keyboard suitable for use while traveling.(notebook)
 - name: desktop-device
   color: fad8c7
   description:  not portable computers, consists of seperate case,monitor,keyboard,mouse.
 - name: tablet-device
   color: 59d683
   description:  portable touchscreen(no keyboard) computers.
 - name: Smartphone-device
   color: 59d683
   description: pocket computers, designed to be used in hand with main function of phone.
 - name: other-device
   color: e99695
   description: mainframes,supercomputer,modem/router or any other computer device
   
 - name: linux-os
   color: c7def8
   description: occur on linux.
 - name: mac-os
   color: c7def8
   description: running on macOS..
 - name: windows-os
   color: c7def8
   description: run on Windows operating system
 - name: android-os
   color: c7def8
   description: using android software platform
 - name: i-os
   color: c7def8
   description: using iOS software platform
   
 - name: behavior-inquiry
   color: ff4400
   description: asking for better understanding of fonctionality
 - name: help-inquiry
   color: ff4400
   description: asking help about unknow fonctionality
 - name: howtodo-inquiry
   color: ff4400
   description: request help for a proper use
   
  - name: crash-trouble
   color: e11d21inquiry
   description: reports premature software terminating.
 - name: freezing-trouble
   color: e6e6e6
   description: infinite blocking loop.
 - name: lag-trouble
   color: e6e6e6
   description: software slowing down the interaction
 - name: glitch-trouble
   color: e6e6e6
   description: short lived fault in the software
 - name: failure-trouble
   color: e6e6e6
   description: includ data loss , errors and warnings
 - name: conflict-trouble
   color: e6e6e6
   description: incompatibility with others software or with specific devices.
 - name: security-trouble
   color: e6e6e6
   description: unwanted expose of privacy or unauthorized privileges access.
   
 - name: option-request
   color: e6e6e6
   description: argunents for including a new option in the settings
 - name: plugin-request
   color: e6e6e6
   description: discusion for new extension,addon,plugin
 - name: menu-request
   color: e6e6e6
   description: suggest to add a new fonction in menu 
 - name: data-request
   color: e6e6e6
   description: aboat creation of any new image,sound,model files
 - name: builtin-request
   color: e6e6e6
   description: idea of new fonctionality integration
   
 - name: remove-sugestion
   color: e6e6e6
   description: suggest to delete an useless exiting feature
 - name: replace-sugestion
   color: e6e6e6
   description: suggest to change an exiting feature by something else
 - name: extend-sugestion
   color: e6e6e6
   description: suggest to add more functionality to an exiting feature
 - name: improve-sugestion
   color: e6e6e6
   description: suggest to enhance performance of an exiting feature
   
 - name: statistics-report
   color: e6e6e6
   description: submit result of statistics
 - name: test-report
   color: e6e6e6
   description: submit result of test
 - name: benchmark-report
   color: e6e6e6
   description: submit result of benchmark
 - name: description-report
   color: e6e6e6
   description: submit result of analyse
 - name: exam-report
   color: f4f19c
   description: submit result of examination
   
 - name: about-language
   color: cc317c
   description: related to localization and translation (i18n)
 - name: about-documentation
   color: b4ea5d
   description: Related to any type of documentation and manual.
 - name: about-client
   color: 0e8a16
   description: concerning the local part of the software
 - name: about-service
   color: 59d683
   description: concerning the distant server application
 - name: about-account
   color: 0052cc
   description: concerning user,player/admin account(login,password authentication)
 - name: about-install
   color: fef2c0
   description: Related to installation on different OS and building from source files
 - name: about-startup
   color: c2e0c6
   description: concern starting process at launch time.
 - name: about-network
   color: f7c6c7
   description: Related to network rfc,protocols conexion.
 - name: about-api
   color: c7def8
   description: Related to Application Programming Interface.
 - name: about-extention
   color: fbca04
   description: concern plugins addons and others extentions
 - name: about-ui
   color: 99cc00
   description: Related to user interface and visual design.
 - name: about-accessibility
   color: dbc2f9
   description: concern about for disabled people
 - name: about-menu
   color: c5def5
   description: options in aplication menu interface
 - name: about-save
   color: fef2c0
   description: Related to records files and backups
 - name: about-open
   color: fef2c0
   description: related to load data files (e.g. opening file for editing)
 - name: about-edit
   color: c5def5
   description: related to files editing
 - name: about-settings
   color: c5def5
   description: about configuration and preferences
 - name: about-files
   color: 0052cc
   description: store organisation for files and directories
 - name: about-data
   color: 0052cc
   description: about not visible audible purpose data 
 - name: about-image
   color: 0052cc
   description: about image pictures icons 
 - name: about-texture
   color: 0052cc
   description: concerning image texture for 3d models
 - name: about-sound
   color: 0052cc
   description: concerning audio fx noises
 - name: about-animation
   color: 0052cc
   description: concerning animation and video movies
 - name: about-3d
   color: 0052cc
   description: concerning 3d vector model shape
 - name: about-logs
   color: c5def5
   description: concerning logs message notification outputs
 - name: about-message
   color: c5def5
   description:  about diplayed notification
 - name: about-physics
   color: 0052cc
   description: about physics  engine
 - name: about-render
   color: 0052cc
   description: about graphic render engine
 - name: about-ai
   color: 0052cc
   description: about artificial inteligencee
 - name: about-pathfinder
   color: 0052cc
   description: about finding path in models
 - name: about-gameplay
   color: 0052cc
   description: define goal and rules of the game,
 - name: about-devlopement
   color: 006400
   description: the project road map and long term plan
 - name: about-license
   color: 006400
   description: license atribution
 - name: about-contribution
   color: 006400
   description: rules and guidlines for contributing.
 - name: about-repository
   color: e6e6e6
   description: concerne repository organisation and management.
