### These settings are synced to GitHub by https://probot.github.io/apps/settings/
### read how to config: https://github.com/probot/settings/blob/master/README.md
### And see https://developer.github.com/v3/repos/#edit for all available settings.

repository:
   
   ## The name of the repository. Changing this will rename the repository
   #name: repo-name
   
   ## A short description of the repository that will show up on GitHub
   #description: This is the description of this github repository.
   
   ## A comma-separated list of topics to set on the repository
   #topics: game,app,art,concept,futur,client,server,network,linux,video,editor,production,engineering,cad,3d
   
   ## A URL with more information about the repository
   #homepage: https://example.github.io/
   

   ## `true` to make the repository private or `false` to make it public.
   #private: false

   ## the default branch for this repository.
   default_branch: master

   ## if true squash all the commits in pull requests for finaly merge only one commit on head of the branch .
   allow_squash_merge: false
   ## allow or not to create a new branch for merging commits in the pull request on the head of the branch.
   allow_merge_commit: false
   ## rebase-merging keep all the commits of the pull requests and add them on the branch head.
   allow_rebase_merge: true
   

   ### Features
   
   ## `true` to integrate the 'task tracking' or `false` to disable it.
   has_issues: true

   ## `true` for enable or `false` to disable the 'projects board'.
   ## (If projects are disabled for the organization, passing `true` will cause an API error.)
   has_projects: false
   ## All of This for Only That... is my thinking when i see the utility of the 'projects board'.
   ## Maybe with required approving review on a pull request 'projects board' will appear more usefull.
   ## for now lets just use milestones and personal 'projects boards'

   ## `true` to enable the wiki or `false` to disable it.
   has_wiki: false
   ## i dont want spend contributions efforts in gh-page AND wiki documentation.
   ## i prefere we focus on just one type of documentation.
   ## gh-page seems easier to integrate in realases for offline documentation and keep the same collaboration process
   ## but GitHub Pages are always public, even if the repo they’re coming form is private. 

   ## Set to true or false to enable/disable the !deprecated! downloads features on the repository..
   #has_downloads: false


   
## define Labels for Issues and Pull Requests
## name: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
## description: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
labels:
   
 - name: referred
   color: ededed
   description: pullrequest applyed on opened issue
 - name: confirmed
   color: ededed
   description: reliable content, confirmed by many people ( can be reproduced if an issue)
 - name: employed
   color: ededed
   description: issues with some pullrequest dedicated about
 - name: duplication
   color: bfdadc
   description: duplicate an already existing issue that have been reported before.
 - name: filled
   color: bfd4f2
   description: Issues reported on the good way. with all fields filled
 - name: irrelevant
   color: fbca04
   description: unrelated improper inappropriate incongruous inept inapt.
   
 - name: type:newfeature
   color: 009800
   description: asking for a new functionality to be added. 
 - name: type:enhancement
   color: 1d76db
   description: ask for modification of an existing feature.
 - name: type:question
   color: cc317c
   description: need help or have something to ask, (e.g. how to do something)
 - name: type:feedback
   color: 006b75
   description: give tests and analyse that could help for project development.
 - name: type:bug
   color: b71c1c
   description: about unintended behaviours that need correction.
   
 - name: priority:high
   color: b60205
   description: important critical Emergency, require urgent action.
 - name: priority:normal
   color: cccccc
   description: concerning common issues.
 - name: priority:low
   color: f9d0c4
   description: trivial and minor topics, will be proced if nothing more serious.
   
 - name: user-level:novice
   color: fc97b2
   description: issues made by beginners contributor
 - name: user-level:average
   color: 7057ff
   description: issues made by intermediate contributor
 - name: user-level:expert
   color: 7057ff
   description: issues made by high experie-languagenced contributor
   
 - name: language:english
   color: 8ed9e2
   description: software language in use
 - name: language:french
   color: 8ed9e2
   description: software language in use
 - name: language:italian
   color: 8ed9e2
   description: software language in use
 - name: language:portuguese
   color: 8ed9e2
   description: software language in use
 - name: language:russian
   color: 8ed9e2
   description: software language in use
 - name: language:spanish
   color: 8ed9e2
   description: software language in use
 - name: language:arabic
   color: 8ed9e2
   description: software language in use
 - name: language:chinese
   color: 8ed9e2
   description: software language in use
   
 - name: version:2.4.3
   color: 8ed9e2
   description: software Version concerned
 - name: version:1.2.3
   color: 8ed9e2
   description: software Version concerned
 - name: version:beta
   color: 8ed9e2
   description: software Version concerned
   
 - name: device:laptop
   color: fad8c7
   description: computers with keyboard suitable for use while traveling.(notebook)
 - name: device:desktop
   color: fad8c7
   description:  not portable computers, consists of seperate case,monitor,keyboard,mouse.
 - name: device:tablet
   color: 59d683
   description: portable touchscreen(no keyboard) computers.
 - name: device:smartphone
   color: 59d683
   description: pocket computers, designed to be used in hand with main function of phone.

   
 - name: os:linux
   color: c7def8
   description: occur on linux.
 - name: os:mac
   color: c7def8
   description: running on macOS..
 - name: os:windows
   color: c7def8
   description: run on Windows operating system
 - name: os:android
   color: c7def8
   description: using android software platform
 - name: os:ios
   color: c7def8
   description: using iOS software platform
   
 - name: inquiry:behavior
   color: ff4400
   description: asking for better understanding of fonctionality
 - name: inquiry:help
   color: ff4400
   description: asking help about unknow fonctionality
 - name: inquiry:howtodo
   color: ff4400
   description: request help for a proper use
   
 - name: trouble:crash
   color: e11d21inquiry
   description: reports premature software terminating.
 - name: trouble:freezing
   color: e6e6e6
   description: infinite blocking loop.
 - name: trouble:lag
   color: e6e6e6
   description: software slowing down the interaction
 - name: trouble:glitch
   color: e6e6e6
   description: short lived fault in the software
 - name: trouble:failure
   color: e6e6e6
   description: includ data loss , errors and warnings
 - name: trouble:conflict
   color: e6e6e6
   description: incompatibility with others software or with specific devices.
 - name: trouble:security
   color: e6e6e6
   description: unwanted expose of privacy or unauthorized privileges access.
   
 - name: request:option
   color: e6e6e6
   description: argunents for including a new option in the settings
 - name: request:plugin
   color: e6e6e6
   description: discusion for new extension,addon,plugin
 - name: request:menu
   color: e6e6e6
   description: suggest to add a new fonction in menu 
 - name: request:data
   color: e6e6e6
   description: aboat creation of any new image,sound,model files
 - name: request:builtin
   color: e6e6e6
   description: idea of new fonctionality integration
   
 - name: suggest:remove
   color: e6e6e6
   description: suggest to delete an useless exiting feature
 - name: suggest:replace
   color: e6e6e6
   description: suggest to change an exiting feature by something else
 - name: suggest:extend
   color: e6e6e6
   description: suggest to add more functionality to an exiting feature
 - name: suggest:improve
   color: e6e6e6
   description: suggest to enhance performance of an exiting feature
   
 - name: report:statistics
   color: e6e6e6
   description: submit result of statistics
 - name: report:test
   color: e6e6e6
   description: submit result of test
 - name: report:benchmark
   color: e6e6e6
   description: submit result of benchmark
 - name: report:description
   color: e6e6e6
   description: submit result of analyse
 - name: report:exam
   color: f4f19c
   description: submit result of examination


