### These settings are synced to GitHub by https://probot.github.io/apps/settings/
### read how to config: https://github.com/probot/settings/blob/master/README.md
### And see https://developer.github.com/v3/repos/#edit for all available settings.

repository:
   
   ## The name of the repository. Changing this will rename the repository
   #name: repo-name
   
   ## A short description of the repository that will show up on GitHub
   #description: This is the description of this github repository.
   
   ## A comma-separated list of topics to set on the repository
   #topics: game,app,art,concept,futur,client,server,network,linux,video,editor,production,engineering,cad,3d
   
   ## A URL with more information about the repository
   #homepage: https://example.github.io/
   

   ## `true` to make the repository private or `false` to make it public.
   #private: false

   ## the default branch for this repository.
   default_branch: master

   ## if true squash all the commits in pull requests for finaly merge only one commit on head of the branch .
   allow_squash_merge: false
   ## allow or not to create a new branch for merging commits in the pull request on the head of the branch.
   allow_merge_commit: false
   ## rebase-merging keep all the commits of the pull requests and add them on the branch head.
   allow_rebase_merge: true
   

   ### Features
   
   ## `true` to integrate the 'task tracking' or `false` to disable it.
   has_issues: true

   ## `true` for enable or `false` to disable the 'projects board'.
   ## (If projects are disabled for the organization, passing `true` will cause an API error.)
   has_projects: false
   ## All of This for Only That... is my thinking when i see the utility of the 'projects board'.
   ## Maybe with required approving review on a pull request 'projects board' will appear more usefull.
   ## for now lets just use milestones and personal 'projects boards'

   ## `true` to enable the wiki or `false` to disable it.
   has_wiki: false
   ## i dont want spend contributions efforts in gh-page AND wiki documentation.
   ## i prefere we focus on just one type of documentation.
   ## gh-page seems easier to integrate in realases for offline documentation and keep the same collaboration process
   ## but GitHub Pages are always public, even if the repo they’re coming form is private. 

   ## Set to true or false to enable/disable the !deprecated! downloads features on the repository..
   #has_downloads: false


   
## define Labels for Issues and Pull Requests
## name: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
## description: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
labels:
   
 - name: employed
   color: 00ffff
   description: issues with some pullrequest dedicated about
 - name: referred
   color: 00ffff
   description: pullrequest applyed on opened issue
 - name: filled
   color: aaffaa
   description: Issues reported on the good way. with all fields filled
 - name: confirmed
   color: 00ff00
   description: reliable content, confirmed by many people ( can be reproduced if an issue)
 - name: duplication
   color: ffaa33
   description: duplicate an already existing issue that have been reported before.
 - name: irrelevant
   color: aa0000
   description: unrelated improper inappropriate incongruous inept inapt.
   
 - name: type:newfeature
   color: 3333aa
   description: asking for a new functionality to be added. 
 - name: type:enhancement
   color: 3333aa
   description: ask for modification of an existing feature.
 - name: type:question
   color: 3333aa
   description: need help or have something to ask, (e.g. how to do something)
 - name: type:feedback
   color: 3333aa
   description: give tests and analyse that could help for project development.
 - name: type:bug
   color: 3333aa
   description: about unintended behaviours that need correction.
   
 - name: priority:high
   color: ff0000
   description: important critical Emergency, require urgent action.
 - name: priority:normal
   color: ffaa00
   description: concerning common issues.
 - name: priority:low
   color: ffff00
   description: trivial and minor topics, will be proced if nothing more serious.
   
 - name: user-level:novice
   color: ffaaff
   description: issues made by beginners contributor
 - name: user-level:average
   color: ff00ff
   description: issues made by intermediate contributor
 - name: user-level:expert
   color: aa00aa
   description: issues made by high experie-languagenced contributor
   
 - name: language:english
   color: 39ffcc
   description: software language in use
 - name: language:french
   color: 39ffcc
   description: software language in use
 - name: language:italian
   color: 39ffcc
   description: software language in use
 - name: language:portuguese
   color: 39ffcc
   description: software language in use
 - name: language:russian
   color: 39ffcc
   description: software language in use
 - name: language:spanish
   color: 39ffcc
   description: software language in use
 - name: language:arabic
   color: 39ffcc
   description: software language in use
 - name: language:chinese
   color: 39ffcc
   description: software language in use
   
 - name: version:2.4.3
   color: 01ff70
   description: software Version concerned
 - name: version:1.2.3
   color: 01ff70
   description: software Version concerned
 - name: version:beta
   color: 01ff70
   description: software Version concerned
   
 - name: device:laptop
   color: 3d9970
   description: computers with keyboard suitable for use while traveling.(notebook)
 - name: device:desktop
   color: 3d9970
   description:  not portable computers, consists of seperate case,monitor,keyboard,mouse.
 - name: device:tablet
   color: 3d9970
   description: portable touchscreen(no keyboard) computers.
 - name: device:smartphone
   color: 3d9970
   description: pocket computers, designed to be used in hand with main function of phone.
   
 - name: os:linux
   color: 2ecc40
   description: occur on linux.
 - name: os:mac
   color: 2ecc40
   description: running on macOS..
 - name: os:windows
   color: 2ecc40
   description: run on Windows operating system
 - name: os:android
   color: 2ecc40
   description: using android software platform
 - name: os:ios
   color: 2ecc40
   description: using iOS software platform
   
 - name: inquiry:behavior
   color: 8888dd
   description: asking for better understanding of fonctionality
 - name: inquiry:help
   color: 8888dd
   description: asking help about unknow fonctionality
 - name: inquiry:howtodo
   color: 8888dd
   description: request help for a proper use
   
 - name: trouble:crash
   color: 8888dd
   description: reports premature software terminating.
 - name: trouble:freezing
   color: 8888dd
   description: infinite blocking loop.
 - name: trouble:lag
   color: 8888dd
   description: software slowing down the interaction
 - name: trouble:glitch
   color: 8888dd
   description: short lived fault in the software
 - name: trouble:failure
   color: 8888dd
   description: includ data loss , errors and warnings
 - name: trouble:conflict
   color: 8888dd
   description: incompatibility with others software or with specific devices.
 - name: trouble:security
   color: 8888dd
   description: unwanted expose of privacy or unauthorized privileges access.
   
 - name: request:option
   color: 8888dd
   description: argunents for including a new option in the settings
 - name: request:plugin
   color: 8888dd
   description: discusion for new extension,addon,plugin
 - name: request:menu
   color: 8888dd
   description: suggest to add a new fonction in menu 
 - name: request:data
   color: 8888dd
   description: aboat creation of any new image,sound,model files
 - name: request:builtin
   color: 8888dd
   description: idea of new fonctionality integration
   
 - name: suggest:remove
   color: 8888dd
   description: suggest to delete an useless exiting feature
 - name: suggest:replace
   color: 8888dd
   description: suggest to change an exiting feature by something else
 - name: suggest:extend
   color: 8888dd
   description: suggest to add more functionality to an exiting feature
 - name: suggest:improve
   color: 8888dd
   description: suggest to enhance performance of an exiting feature
   
 - name: report:statistics
   color: 8888dd
   description: submit result of statistics
 - name: report:test
   color: 8888dd
   description: submit result of test
 - name: report:benchmark
   color: 8888dd
   description: submit result of benchmark
 - name: report:description
   color: 8888dd
   description: submit result of analyse
 - name: report:exam
   color: 8888dd
   description: submit result of examination
   
 - name: about:language
   color: ccccff
   description: related to localization and translation (i18n)
 - name: about:documentation
   color: ccccff
   description: Related to any type of documentation and manual.
 - name: about:client
   color: ccccff
   description: concerning the local part of the software
 - name: about:service
   color: ccccff
   description: concerning the distant server application
 - name: about:account
   color: ccccff
   description: concerning user,player/admin account(login,password authentication)
 - name: about:install
   color: ccccff
   description: Related to installation on different OS and building from source files
 - name: about:startup
   color: ccccff
   description: concern starting process at launch time.
 - name: about:network
   color: ccccff
   description: Related to network rfc,protocols conexion.
 - name: about:api
   color: ccccff
   description: Related to Application Programming Interface.
 - name: about:extention
   color: ccccff
   description: concern plugins addons and others extentions
 - name: about:ui
   color: ccccff
   description: Related to user interface and visual design.
 - name: about:accessibility
   color: ccccff
   description: concern about for disabled people
 - name: about:menu
   color: ccccff
   description: options in aplication menu interface
 - name: about:save
   color: ccccff
   description: Related to records files and backups
 - name: about:open
   color: ccccff
   description: related to load data files (e.g. opening file for editing)
 - name: about:edit
   color: ccccff
   description: related to files editing
 - name: about:settings
   color: ccccff
   description: about configuration and preferences
 - name: about:files
   color: ccccff
   description: store organisation for files and directories
 - name: about:data
   color: ccccff
   description: about not visible audible purpose data 
 - name: about:image
   color: ccccff
   description: about image pictures icons 
 - name: about:texture
   color: ccccff
   description: concerning image texture for 3d models
 - name: about:sound
   color: ccccff
   description: concerning audio fx noises
 - name: about:animation
   color: ccccff
   description: concerning animation and video movies
 - name: about:3d
   color: ccccff
   description: concerning 3d vector model shape
 - name: about:logs
   color: ccccff
   description: concerning logs message notification outputs
 - name: about:message
   color: ccccff
   description:  about diplayed notification
 - name: about:physics
   color: ccccff
   description: about physics  engine
 - name: about:render
   color: ccccff
   description: about graphic render engine
 - name: about:ai
   color: ccccff
   description: about artificial inteligencee
 - name: about:pathfinder
   color: ccccff
   description: about finding path in models
 - name: about:gameplay
   color: ccccff
   description: define goal and rules of the game,
 - name: about:devlopement
   color: ccccff
   description: the project road map and long term plan
 - name: about:license
   color: ccccff
   description: license atribution
 - name: about:contribution
   color: ccccff
   description: rules and guidlines for contributing.
 - name: about:repository
   color: ccccff
   description: concerne repository organisation and management.
